import AccordionTheme from '../Accordion/AccordionTheme';
import AnchorTheme from '../Anchor/AnchorTheme';
import BoxTheme from '../Box/BoxTheme';
import ButtonTheme from '../Button/ButtonTheme';
import CalendarTheme from '../Calendar/CalendarTheme';
import CarouselTheme from '../Carousel/CarouselTheme';
import ChartTheme from '../Chart/ChartTheme';
import CheckBoxTheme from '../CheckBox/CheckBoxTheme';
import ClockTheme from '../Clock/ClockTheme';
import CollapsibleTheme from '../Collapsible/CollapsibleTheme';
import DataTableTheme from '../DataTable/DataTableTheme';
import DiagramTheme from '../Diagram/DiagramTheme';
import DropTheme from '../Drop/DropTheme';
import FormFieldTheme from '../FormField/FormFieldTheme';
import GrommetTheme from '../Grommet/GrommetTheme';
import HeadingTheme from '../Heading/HeadingTheme';
import IconTheme from '../Icon/IconTheme';
import LayerTheme from '../Layer/LayerTheme';
import ListTheme from '../List/ListTheme';
import MaskedInputTheme from '../MaskedInput/MaskedInputTheme';
import MenuTheme from '../Menu/MenuTheme';
import MeterTheme from '../Meter/MeterTheme';
import ParagraphTheme from '../Paragraph/ParagraphTheme';
import RadioButtonTheme from '../RadioButton/RadioButtonTheme';
import RangeInputTheme from '../RangeInput/RangeInputTheme';
import RangeSelectorTheme from '../RangeSelector/RangeSelectorTheme';
import SelectTheme from '../Select/SelectTheme';
import TabTheme from '../Tab/TabTheme';
import TableTheme from '../Table/TableTheme';
import TabsTheme from '../Tabs/TabsTheme';
import TextTheme from '../Text/TextTheme';
import TextAreaTheme from '../TextArea/TextAreaTheme';
import TextInputTheme from '../TextInput/TextInputTheme';
import VideoTheme from '../Video/VideoTheme';
import WorldMapTheme from '../WorldMap/WorldMapTheme';
import GlobalTheme from './GlobalTheme';

export default interface ThemeType {
  dark?: boolean;
  global: GlobalTheme;
  accordion: AccordionTheme;
  anchor: AnchorTheme;
  box: BoxTheme;
  button: ButtonTheme;
  calendar: CalendarTheme;
  carousel: CarouselTheme;
  chart: ChartTheme;
  checkBox: CheckBoxTheme;
  clock: ClockTheme;
  collapsible: CollapsibleTheme;
  dataTable: DataTableTheme;
  diagram: DiagramTheme;
  drop: DropTheme;
  formField: FormFieldTheme;
  grommet: GrommetTheme;
  heading: HeadingTheme;
  icon: IconTheme;
  layer: LayerTheme;
  list: ListTheme;
  maskedInput: MaskedInputTheme;
  menu: MenuTheme;
  meter: MeterTheme;
  paragraph: ParagraphTheme;
  radioButton: RadioButtonTheme;
  rangeInput: RangeInputTheme;
  rangeSelector: RangeSelectorTheme;
  select: SelectTheme;
  tab: TabTheme;
  tabs: TabsTheme;
  table: TableTheme;
  text: TextTheme;
  textArea: TextAreaTheme;
  textInput: TextInputTheme;
  video: VideoTheme;
  worldMap: WorldMapTheme;
}
