import { ChartTheme } from '../../themes/cobalt/chart';
import { CheckBoxTheme } from '../../themes/cobalt/checkBox';
import { CollapsibleTheme } from '../../themes/cobalt/collapsible';
import { FormFieldTheme } from '../../themes/cobalt/formField';
import { GrommetTheme } from '../../themes/cobalt/grommet';
import { MenuTheme } from '../../themes/cobalt/menu';
import { RadioButtonTheme } from '../../themes/cobalt/radioButton';
import { RangeInputTheme } from '../../themes/cobalt/rangeInput';
import { TabTheme } from '../../themes/cobalt/tab';
import { TabsTheme } from '../../themes/cobalt/tabs';
import AccordionTheme from '../components/Accordion/AccordionTheme';
import AnchorTheme from '../components/Anchor/AnchorTheme';
import BoxTheme from '../components/Box/BoxTheme';
import ButtonTheme from '../components/Button/ButtonTheme';
import CalendarTheme from '../components/Calendar/CalendarTheme';
import CarouselTheme from '../components/Carousel/CarouselTheme';
import ClockTheme from '../components/Clock/ClockTheme';
import DataTableTheme from '../components/DataTable/DataTableTheme';
import DiagramTheme from '../components/Diagram/DiagramTheme';
import DropTheme from '../components/Drop/DropTheme';
import HeadingTheme from '../components/Heading/HeadingTheme';
import IconTheme from '../components/Icon/IconTheme';
import LayerTheme from '../components/Layer/LayerTheme';
import ListTheme from '../components/List/ListTheme';
import MaskedInputTheme from '../components/MaskedInput/MaskedInputTheme';
import MeterTheme from '../components/Meter/MeterTheme';
import ParagraphTheme from '../components/Paragraph/ParagraphTheme';
import RangeSelectorTheme from '../components/RangeSelector/RangeSelectorTheme';
import SelectTheme from '../components/Select/SelectTheme';
import TableTheme from '../components/Table/TableTheme';
import TextTheme from '../components/Text/TextTheme';
import TextAreaTheme from '../components/TextArea/TextAreaTheme';
import TextInputTheme from '../components/TextInput/TextInputTheme';
import GlobalTheme from '../components/Theme/GlobalTheme';
import VideoTheme from '../components/Video/VideoTheme';
import WorldMapTheme from '../components/WorldMap/WorldMapTheme';

export default interface ThemeType {
  global: GlobalTheme;
  accordion: AccordionTheme;
  anchor: AnchorTheme;
  box: BoxTheme;
  button: ButtonTheme;
  calendar: CalendarTheme;
  carousel: CarouselTheme;
  chart: ChartTheme;
  checkBox: CheckBoxTheme;
  clock: ClockTheme;
  collapsible: CollapsibleTheme;
  dataTable: DataTableTheme;
  diagram: DiagramTheme;
  drop: DropTheme;
  formField: FormFieldTheme;
  grommet: GrommetTheme;
  heading: HeadingTheme;
  icon: IconTheme;
  layer: LayerTheme;
  list: ListTheme;
  maskedInput: MaskedInputTheme;
  menu: MenuTheme;
  meter: MeterTheme;
  paragraph: ParagraphTheme;
  radioButton: RadioButtonTheme;
  rangeInput: RangeInputTheme;
  rangeSelector: RangeSelectorTheme;
  select: SelectTheme;
  tab: TabTheme;
  tabs: TabsTheme;
  table: TableTheme;
  text: TextTheme;
  textArea: TextAreaTheme;
  textInput: TextInputTheme;
  video: VideoTheme;
  worldMap: WorldMapTheme;
}
